id: PF5EBF866
initial_creation_type: input
source_metadata:
  title: Khenmo Rigdzin Chödrön Series
  language: bo
  description: 'Texts by Khenmo Rigdzin Chödrön (mkhan mo rig ''dzin chos sgron) of
    Larung Gar:'
  volume:
    c9c5e1128a174b018313fb782bcfa361:
      title: An Exhortation to Tibetans
      parent: Advice
created_at: '2022-03-01T00:23:39.357395'
last_modified_at: '2022-03-01T00:23:39.357397'
statistics:
  total_words: 317
  total_non_words: 41
quality:
  non_words_ratio: 0.13
